### ISSUE TITLE
buzzer GPIO setup help?

### ISSUE THREAD

**Issue by VeggieVampire** [kenakofer/pi-bowl#2]
Could you make a circuit diagram for the buzzers?

**Comment by derekpock** [comment]
Kenan, I could attempt to do this, but you have a better understanding of it.

If he doesn't respond in a few days, I'll see what I can do.

**Comment by kenakofer** [comment]
It's very simple. Each buzzer is a button that connects a single gpio pin
to ground. The code sets up the gpio pins to detect when a button was
pressed. Just ask if you need more info.

**Comment by derekpock** [comment]
He might need to know the specific GPIO pins, which ones you used on what model of the Pi.

**Comment by VeggieVampire** [comment]
I have grounded every pin listed below made sure the Open buzzer is checked but still unable to generate an active buzzer click.. Any help would greatly appreciated. Note I have tried GPIO13(pin33) and pin 13 which is GPIO027.. I am using a Pi 2 for the hardware.
pins=[13, 15, 16, 18, 22, 3, 5, 7, 11, 12]

Also I checked with a LED to ground for if power was getting from any of the none powered GPIO pins and no power was being sent out so not sure how it would get a signal to show if it was open or closed.

**Comment by kenakofer** [comment]
Our builds used the Pi and model B, which has fewer and different pins than
model 2 if I remember correctly. With that in mind,  you should change the
array of pins in your code to match the number of each gpio pin you want to
use on the Pi 2. I want to stress that I don't own a Pi 2 and don't know
enough about them to confirm that other aspects of the program will work as
planned. Try grounding just one of the pins at a time. Does the code run
without errors?

**Comment by VeggieVampire** [comment]
I found the problem you must force the constant for virtualized to be False. on line 9. and all starts to work. :)

virtualized=False

**Comment by VeggieVampire** [comment]
I use pins=[7, 11, 12, 13, 15, 16, 18, 22, 29, 31] for a pi 2

**Comment by derekpock** [comment]
Fantastic! Glad it works! Be sure to ask if you have any more questions, and feel free to improve the software as well! I'm no longer in a position to actively use this, so any suggestions is appreciated and welcome.
